CREATE TABLE IF NOT EXISTS `USER` (

    `ID` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `USERNAME` varchar(MAX) NOT NULL,
    `ADDRESS` varchar(MAX) NOT NULL,
    `EMAIL` varchar(2000) NOT NULL,
    `FIRSTNAME` varchar(1000) NOT NULL,
    `LASTNAME` varchar(200) NOT NULL,
    `DATEOFBIRTH` DATE

);